name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install --yes codespell
      - uses: actions/checkout@v4
      - run: codespell content

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: make docker
